// flow-typed signature: 5ab6b0b5681b95e11016243e7c1e27d1
// flow-typed version: <<STUB>>/history-server_v^1.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'history-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'history-server/apps/one/index' {
  declare module.exports: any;
}

declare module 'history-server/apps/two/index' {
  declare module.exports: any;
}

declare module 'history-server/apps/two/three/index' {
  declare module.exports: any;
}

declare module 'history-server/config' {
  declare module.exports: any;
}

declare module 'history-server/history-server' {
  declare module.exports: any;
}

declare module 'history-server/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'history-server/apps/one/index.js' {
  declare module.exports: $Exports<'history-server/apps/one/index'>;
}
declare module 'history-server/apps/two/index.js' {
  declare module.exports: $Exports<'history-server/apps/two/index'>;
}
declare module 'history-server/apps/two/three/index.js' {
  declare module.exports: $Exports<'history-server/apps/two/three/index'>;
}
declare module 'history-server/config.js' {
  declare module.exports: $Exports<'history-server/config'>;
}
declare module 'history-server/history-server.js' {
  declare module.exports: $Exports<'history-server/history-server'>;
}
declare module 'history-server/index' {
  declare module.exports: $Exports<'history-server'>;
}
declare module 'history-server/index.js' {
  declare module.exports: $Exports<'history-server'>;
}
declare module 'history-server/server.js' {
  declare module.exports: $Exports<'history-server/server'>;
}
