// flow-typed signature: 8a66619d9e5ebc2730d0c23aaf5b3a9b
// flow-typed version: <<STUB>>/wc-loader_v^1.1.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wc-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wc-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wc-loader/lib/index' {
  declare module.exports: any;
}

declare module 'wc-loader/lib/renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wc-loader/index' {
  declare module.exports: $Exports<'wc-loader'>;
}
declare module 'wc-loader/index.js' {
  declare module.exports: $Exports<'wc-loader'>;
}
declare module 'wc-loader/lib/index.js' {
  declare module.exports: $Exports<'wc-loader/lib/index'>;
}
declare module 'wc-loader/lib/renderer.js' {
  declare module.exports: $Exports<'wc-loader/lib/renderer'>;
}
