// flow-typed signature: 518a361b64fbc5e613f2fa34f4bada56
// flow-typed version: <<STUB>>/webpack-copy-plugin_v^0.0.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-copy-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-copy-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-copy-plugin/index' {
  declare module.exports: $Exports<'webpack-copy-plugin'>;
}
declare module 'webpack-copy-plugin/index.js' {
  declare module.exports: $Exports<'webpack-copy-plugin'>;
}
